config/routes.rb
Pinteresting::Application.routes.draw do
  resources :hobbies
  get 'hobbies/:id/add' => 'hobbies#add', as: :add
  get 'hobbies/:id/subtract' => 'hobbies#subtract',as: :subtract
  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # creates about_path
  

  

  

end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :hobbies
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /hobbies
  # GET /hobbies.json
  def index
    @hobbies = Hobby.all
  end

  # GET /hobbies/1
  # GET /hobbies/1.json
  def show
  end

  # GET /hobbies/new
  def new
    @hobby = current_user.hobbies.build
  end

  # GET /hobbies/1/edit
  # GET /hobbies/1/edit
  def edit
  end

  # POST /hobbies
  # POST /hobbies.json
  def create
    @hobby = current_user.hobbies.build(hobby_params)
    @hobby.hours = 0
    @hoby.amount = 0
    if @hobby.save
      redirect_to @hobby, notice: 'Hobby was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /hobbies/1
  # PATCH/PUT /hobbies/1.json
  def update
    if @hobby.update(hobby_params)
      redirect_to @hobby, notice: 'Hobby was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /hobbies/1
  # DELETE /hobbies/1.json
  def destroy
    @hobby.destroy
    redirect_to hobbies_url
  end

  # GET /hobbies/1/add
  def add(amount)
    @hobby.hours += (amount)
  end

  # GET /hobbies/1/subtract
  def subtract(amount)
    @hobby.hours -= (amount)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hobby
      @hobby = Hobby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hobby_params
      params.require(:hobby).permit(:name, :description, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :created_at)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/hobbies/_form.html.erb
<%= form_for(@hobby) do |f| %>
  <% if @hobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hobby.errors.count, "error") %> prohibited this hobby from being saved:</h2>

      <ul>
      <% @hobby.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name, :required => true, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :required => true, class: "form-control" %>
  </div>
  <br>
  <div class="panel panel-default">
    <div class="panel-heading">Hours</div>
      <table class="table">
          <tr>
            <td><%= f.label :sunday %></td>
            <td><%= f.label :monday %></td>
            <td><%= f.label :tuesday %></td>
            <td><%= f.label :wednesday %></td>
            <td><%= f.label :thursday %></td>
            <td><%= f.label :friday %></td>
            <td><%= f.label :saturday %></td>
            <td><%= f.label :remind_me_with_Twilio %></td>
          </tr>
          <tr>
            <td><%= f.text_field :sunday, :required => true %></td>
            <td><%= f.text_field :monday, :required => true %></td>
            <td><%= f.text_field :tuesday, :required => true %></td>
            <td><%= f.text_field :wednesday, :required => true %></td>
            <td><%= f.text_field :thursday, :required => true %></td>
            <td><%= f.text_field :friday, :required => true %></td>
            <td><%= f.text_field :saturday, :required => true %></td>
            <td><input type="text" placeholder="Phone number"></input></td>
          </tr>
      </table>
    </div>
  <div class="field" style="display:none">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hobbies/add.html.erb
<% if user_signed_in? %>
<h1>Editing hobby</h1>

<%= render 'form' %>
<br>
<%= link_to "Show", @hobby, class: "btn btn-success" %>
<%= link_to "Back", hobbies_path, class: "btn btn-warning" %>
<% else %>
  <h1>You must signin or sign up</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg" %>
  </p>
<% end %>

app/views/hobbies/edit.html.erb
<% if user_signed_in? %>
<h1>Editing hobby</h1>

<%= render 'form' %>
<br>
<%= link_to "Show", @hobby, class: "btn btn-success" %>
<%= link_to "Back", hobbies_path, class: "btn btn-warning" %>
<% else %>
	<h1>You must signin or sign up</h1>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	 	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg" %>
	</p>
<% end %>

app/views/hobbies/index.html.erb
<% if user_signed_in? %>
<h1>Your hobbies</h1>
<div class="panel panel-default">
  <div class="panel-heading">Hours completed in your hobby</div>
  <table class="table table-condensed">
    <thead>
    <tr>
      <th>test slot</th>
      <th>Name</th>
      <th>Description</th>
      <th>Sunday</th>
      <th>Monday</th>
      <th>Tuesday</th>
      <th>Wednesday</th>
      <th>Thursday</th>
      <th>Friday</th>
      <th>Saturday</th>
      <th>Created</th>
      <th>Weekly Hours</th>
      <th>Twilio reminder</th>
    </tr>
    </thead>
    <tbody>
    <% current_user.hobbies.each do |hobby| %>
      <tr>
        <td><%= hobby.hours %></td>
        <td><%= hobby.name %></td>
        <td><%= hobby.description %></td>
        <td><%= hobby.sunday %></td>
        <td><%= hobby.monday %></td>
        <td><%= hobby.tuesday %></td>
        <td><%= hobby.wednesday %></td>
        <td><%= hobby.thursday %></td>
        <td><%= hobby.friday %></td>
        <td><%= hobby.saturday %></td>
        <td><%= hobby.created_at %></td>
        <td><%= hobby.sunday + hobby.monday + hobby.tuesday + hobby.wednesday + hobby.thursday + hobby.friday + hobby.saturday %></td>
        <% if hobby.user == current_user %>
        <td><input type="checkbox" checked></input></td>
        <td><%= link_to "Show", hobby, class: "btn btn-success" %></td>
        <td><%= link_to "Edit", edit_hobby_path(hobby), class: "btn btn-warning" %></td>
        <td><%= link_to "Delete", hobby, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <td><%= link_to "add hours", add_path(hobby), class: "btn btn-info" %></td>
        <td><%= link_to "subtract hours", subtract_path(hobby), class: "btn btn-info" %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to "New Hobby", new_hobby_path, class: "btn btn-success" %>
<% else %>
  <h1>Please Sign in or Sign up</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg" %>
  </p>
<% end %>

app/views/hobbies/new.html.erb
<% if user_signed_in? %>
<h1>New hobby</h1>

<%= render 'form' %>

<br>

<button class="button button-positive"><%= link_to 'Back', hobbies_path %></button>
<% else %>
	<h1>you must signin or sign up</h1>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	 	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg" %>
	</p>
<% end %>

app/views/hobbies/show.html.erb
<% if user_signed_in? %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hobby.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hobby.description %>
</p>

<p>
  <strong>Sunday:</strong>
  <%= @hobby.sunday %>
</p>

<p>
  <strong>Monday:</strong>
  <%= @hobby.monday %>
</p>

<p>
  <strong>Tuesday:</strong>
  <%= @hobby.tuesday %>
</p>

<p>
  <strong>Wednesday:</strong>
  <%= @hobby.wednesday %>
</p>

<p>
  <strong>Thursday:</strong>
  <%= @hobby.thursday %>
</p>

<p>
  <strong>Friday:</strong>
  <%= @hobby.friday %>
</p>

<p>
  <strong>Saturday:</strong>
  <%= @hobby.saturday %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @hobby.created_at %>
</p>

<button class="button button-positive"><%= link_to 'Edit', edit_hobby_path(@hobby) %></button>
<button class="button button-energized"><%= link_to 'Back', hobbies_path %></button>
<% else %>
  <h1>you must signin or sign up</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg" %>
  </p>
<% end %>

app/views/hobbies/subtract.html.erb
<% if user_signed_in? %>
<h1>Editing hobby</h1>

<%= render 'form' %>
<br>
<%= link_to "Show", @hobby, class: "btn btn-success" %>
<%= link_to "Back", hobbies_path, class: "btn btn-warning" %>
<% else %>
	<h1>You must signin or sign up</h1>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	 	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg" %>
	</p>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Practice Makes Perfect", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Hobbies", hobbies_path %></li>
          <li><%= link_to "Account settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeMakesPerfect</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render "layouts/header" %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Practice makes perfect</h1>
	<p>Put in 10,000 hours to become an expert in whatever!</p>
	<p>
		 <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		 <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-lg" %>
	</p>
</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<br>
<div class="jumbotron center">
	<span class="why"><h3>Created by <a href="http://aeipsapps.tumblr.com"><b>Stasy Meclazcke</b></a>, <a href="http://github.com/samsatre"><b>Sam Satre</b></a>, and <a href="http://cmacca.github.io"><b>Colin McIllece</b></a></h3></span>
	<h4>Three <b>high school</b> web and app developers who love to <b>create</b> and put ideas into action. This website was created as a project for HShacks (link below)</h4>
	<div id="movelefte">
		<h4>The hackathon</h4>
		<p><%= link_to "Here", "http://www.hshacks.com", class: "btn btn-primary btn-lg" %></p>
	</div>
	<div id="moverighte">
		<h4>The code</h4>
		<p><%= link_to "Here", "https://github.com/aeip/practicemakesperfect", class: "btn btn-primary btn-lg" %></p>
	</div>
	<h2>
	What Does it do?
	</h2>
	<p>
	<h4>Practice Makes Perfect</b> (PMP) makes use of Malcom Gladwell's 10,000 hour concept. The concept states that it takes approximately 10,000 hours to become an expert in an activity. PMP takes that concept and creates a list and calendar for you to follow in order to achieve your goal of 10,000 hours. You can set tasks to occur every day in advance so you become motivated to complete them. You can also add new hours to the queue if you happened to work more or less on that goal during a day.
	</h4>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Practice makes <b>perfect</b></h1>
	<p>It takes 10,000 hours to become an expert in something</p>
	<p>Get ready to track your hours and become an expert.</p>
	<% if user_signed_in? == false %>
	<p>
		<%= link_to "Sign in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
	<% end %>
</div>